[package]
   name = "cpcli"
   version = "0.0.2"
   description = "c++ command line parser library"

[lib]
   name = "cpcli"
   type = "static"
   source = ["src/command.cpp"]

[[example]]
    name = "test"
    source = ["example/example.cpp"]

[[example]]
    name = "tt"
    source = ["example/test.cpp"]

[[example]]
    name = "parse"
    source = ["example/parser.cpp"]

#[[test]]
#    name = "parse test"
#    source = ["test/test.cpp"]


[dependencies]
    serdepp="0.1.3"
    fmt="8.0.1"

[dev-dependencies]
    Catch2="2.9.1" 
    nlohmann_json="3.9.1"

